Parameters:
  BucketName:
    Type: String
    Default: flask-app-cicd-bucket-arongeerts
    Description: The Bucket name

Resources:
  CodeS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
